### ISSUE TITLE
Make universal seperate UI for buttons and basic widgets.

### ISSUE THREAD

**Issue by Jiggy9** [Jiggy9/JCT#1]
Make seperate widget for diffferent kind of buttongs and all.. make it more user friendly and readable code.. improve as much you can.

**Comment by ritik6559** [comment]
i can work on it.

**Comment by Jiggy9** [comment]
> i can work on it.

You can start working now @ritik6559

**Comment by ritik6559** [comment]
please add the label of gssoc and haktoberfest and can you please assign a level to it.

**Comment by ritik6559** [comment]
do you have any design idea on your mind or i have to go with the same ui?

**Comment by Jiggy9** [comment]
> do you have any design idea on your mind or i have to go with the same ui?

Not really, If you can make it better send me ss of samples and I'll tell you if it's related to project then I'll approve it.

**Comment by ritik6559** [comment]
What is the base color of your app blue only?

**Comment by Jiggy9** [comment]
> What is the base color of your app blue only?

Yes I want classic but uder friendly and smooth UI.. also it's better to communicate over LinkedIn, could u just drop msg me there.

**Comment by ritik6559** [comment]
send me your profile link

**Comment by ritik6559** [comment]
mine is:- [https://www.linkedin.com/in/ritik-joshi-672a962aa/]

**Comment by arshmandal0725** [comment]
please assign this issue to me

**Comment by Jiggy9** [comment]
> please assign this issue to me

do you have any perticular design in your mind?

**Comment by ritik6559** [comment]
hey work is done but while committing, it is showing access not granted so can you grant me access or can you create a new branch

**Comment by Jiggy9** [comment]
#21 completed
