### ISSUE TITLE
Adding feedback option

### ISSUE THREAD

**Issue by Aditijainnn** [Jiggy9/JCT#10]
Add feedback /rate us 
assign this issue to me under gssoc ext and hacktoberfest

**Comment by CodewithAnn** [comment]
@Jiggy9 **Work is done👍! Assign this to me so that I can raise a pull request.** 
All the Feedback is going to be saved in the Database
### Choose which one is looking good or any other suggestions.

<img src="https://github.com/user-attachments/assets/7abaf78f-53ef-453a-bce1-e233fc626fa8" alt="Screenshot" width="250">, <img src="https://github.com/user-attachments/assets/3a45c7a1-ff19-4713-8767-213dbf1e36c9" alt="Screenshot" width="250">

**Comment by Jiggy9** [comment]
@Aditijainnn if you've already worked on it lemme know or I'll assign someone else as other contributors are willing to contribute too.

**Comment by Aditijainnn** [comment]
> @Aditijainnn if you've already worked on it lemme know or I'll assign someone else as other contributors are willing to contribute too.

yes i am working on it

**Comment by Aditijainnn** [comment]
> @Jiggy9 **Work is done👍! Assign this to me so that I can raise a pull request.** All the Feedback is going to be saved in the Database
> ### Choose which one is looking good or any other suggestions.
> 
> <img alt="Screenshot" width="250" src="https://private-user-images.githubusercontent.com/94635707/374114218-7abaf78f-53ef-453a-bce1-e233fc626fa8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzMDE0NDQsIm5iZiI6MTcyODMwMTE0NCwicGF0aCI6Ii85NDYzNTcwNy8zNzQxMTQyMTgtN2FiYWY3OGYtNTNlZi00NTNhLWJjZTEtZTIzM2ZjNjI2ZmE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA3VDExMzkwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkMDdhNTEyZjY5NmY5M2Q2ZmUzNTA4NzU2OGJkYjkyYWNmODljNmM5OGVkOGU3ZWM1YzU0NTQwYmMxOTE2YzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.pSQt-zJ5devinFCtH0wbdv_EfeteThVRHBivEDhJTtE">, <img alt="Screenshot" width="250" src="https://private-user-images.githubusercontent.com/94635707/374114327-3a45c7a1-ff19-4713-8767-213dbf1e36c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzMDE0NDQsIm5iZiI6MTcyODMwMTE0NCwicGF0aCI6Ii85NDYzNTcwNy8zNzQxMTQzMjctM2E0NWM3YTEtZmYxOS00NzEzLTg3NjctMjEzZGJmMWUzNmM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA3VDExMzkwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2NzYwMzllYjYwMTdjM2QwY2JkMGFhM2UyNzg5NzMzZjUzYjM1NWY5N2VmNDM3N2JiNWQ0ZjM3NzkyNTBiNDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.2QKXWeD_q9RcFOxGV4-FTeFKf0JvcX9b0AixA9D6Q_s">

second one

**Comment by CodewithAnn** [comment]
> > @Jiggy9 **Work is done👍! Assign this to me so that I can raise a pull request.** All the Feedback is going to be saved in the Database
> > ### Choose which one is looking good or any other suggestions.
> > <img alt="Screenshot" width="250" src="https://private-user-images.githubusercontent.com/94635707/374114218-7abaf78f-53ef-453a-bce1-e233fc626fa8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzMDE0NDQsIm5iZiI6MTcyODMwMTE0NCwicGF0aCI6Ii85NDYzNTcwNy8zNzQxMTQyMTgtN2FiYWY3OGYtNTNlZi00NTNhLWJjZTEtZTIzM2ZjNjI2ZmE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA3VDExMzkwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkMDdhNTEyZjY5NmY5M2Q2ZmUzNTA4NzU2OGJkYjkyYWNmODljNmM5OGVkOGU3ZWM1YzU0NTQwYmMxOTE2YzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.pSQt-zJ5devinFCtH0wbdv_EfeteThVRHBivEDhJTtE">, <img alt="Screenshot" width="250" src="https://private-user-images.githubusercontent.com/94635707/374114327-3a45c7a1-ff19-4713-8767-213dbf1e36c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzMDE0NDQsIm5iZiI6MTcyODMwMTE0NCwicGF0aCI6Ii85NDYzNTcwNy8zNzQxMTQzMjctM2E0NWM3YTEtZmYxOS00NzEzLTg3NjctMjEzZGJmMWUzNmM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA3VDExMzkwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2NzYwMzllYjYwMTdjM2QwY2JkMGFhM2UyNzg5NzMzZjUzYjM1NWY5N2VmNDM3N2JiNWQ0ZjM3NzkyNTBiNDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.2QKXWeD_q9RcFOxGV4-FTeFKf0JvcX9b0AixA9D6Q_s">
> 
> second one also in this i can add rating out of 5 star feature

already done 😅

**Comment by Jiggy9** [comment]
> > @Aditijainnn if you've already worked on it lemme know or I'll assign someone else as other contributors are willing to contribute too.
> 
> yes i am working on it

What's ur progress till now.. also send me ss of you've design

**Comment by Aditijainnn** [comment]
> > > @Aditijainnn if you've already worked on it lemme know or I'll assign someone else as other contributors are willing to contribute too.
> > 
> > 
> > yes i am working on it
> 
> What's ur progress till now.. also send me ss of you've design

![image](https://github.com/user-attachments/assets/06e63468-c790-4852-88e3-91827d3f9dcf)
 in this browse file is there and ui can be improved

**Comment by Jiggy9** [comment]
> > > > @Aditijainnn if you've already worked on it lemme know or I'll assign someone else as other contributors are willing to contribute too.
> > > 
> > > 
> > > yes i am working on it
> > 
> > 
> > What's ur progress till now.. also send me ss of you've design
> 
> ![image](https://private-user-images.githubusercontent.com/144632601/374193783-06e63468-c790-4852-88e3-91827d3f9dcf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzMTA1ODgsIm5iZiI6MTcyODMxMDI4OCwicGF0aCI6Ii8xNDQ2MzI2MDEvMzc0MTkzNzgzLTA2ZTYzNDY4LWM3OTAtNDg1Mi04OGUzLTkxODI3ZDNmOWRjZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwN1QxNDExMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NWJmZWU5YzE2MWVjY2E5YzQ1ODI1MGJhMGUxYTdlMTU1NjY1YTUzZTgwOGEyMzlhZWVlY2VhZmMxNmJlMDJmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.p52pJv5JDilCEDmvopPeG632-2trKLpe72ZVGgrLNmQ) in this browse file is there and ui can be improved

Send me android one, also design is very simple, this is final design? And lemme know and data will be reflectd in firebase?

**Comment by CodewithAnn** [comment]
> > > > @Aditijainnn if you've already worked on it lemme know or I'll assign someone else as other contributors are willing to contribute too.
> > > 
> > > 
> > > yes i am working on it
> > 
> > 
> > What's ur progress till now.. also send me ss of you've design
> 
> ![image](https://private-user-images.githubusercontent.com/144632601/374193783-06e63468-c790-4852-88e3-91827d3f9dcf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzMTA3NTAsIm5iZiI6MTcyODMxMDQ1MCwicGF0aCI6Ii8xNDQ2MzI2MDEvMzc0MTkzNzgzLTA2ZTYzNDY4LWM3OTAtNDg1Mi04OGUzLTkxODI3ZDNmOWRjZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwN1QxNDE0MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYmNiODZhN2I3NzgzMGVmNzRhNzJkMThhMjExNmNkMzNkMDA0Y2I0MDJhNmU2MDQ0MDExMzc4OGI2YzdkZDQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.7DtIIGjn1bL3t5vBumt_3nluFPWQcHTJwU1Gsv35SNc) in this browse file is there and ui can be improved

are you using Html or ejs to build this?

**Comment by CodewithAnn** [comment]
@Jiggy9  assign this issue to me

**Comment by Jiggy9** [comment]
> @Jiggy9 assign this issue to me

You can work on this issue now

**Comment by Jiggy9** [comment]
#22 completed
