### ISSUE TITLE
there is no about section in the app and also there is bottom overflow in the buttons of the app

### ISSUE THREAD

**Issue by RilAbbSnehaM** [Jiggy9/JCT#14]

**Comment by Jiggy9** [comment]
@RilAbbSnehaM  Show me screenshot of buttons overflow of the app

**Comment by RilAbbSnehaM** [comment]
![WhatsApp Image 2024-10-07 at 22 10 45_3d48ebc6](https://github.com/user-attachments/assets/6d7d82e6-9b36-4055-adcd-cb50f71c3e98)

**Comment by Jiggy9** [comment]
@RilAbbSnehaM you can start work on this issue

**Comment by RilAbbSnehaM** [comment]
https://github.com/user-attachments/assets/4d171e80-6915-4401-8386-0d0f4fb36fda

![WhatsApp Image 2024-10-07 at 22 36 00_82548d18](https://github.com/user-attachments/assets/9b86a358-2a5a-44d9-9d1e-c2c6a7ececd7)

**Comment by RilAbbSnehaM** [comment]
@Jiggy9 done

**Comment by Jiggy9** [comment]
> @Jiggy9 done

Great, send pull request.

**Comment by RilAbbSnehaM** [comment]
@Jiggy9 done pull request

**Comment by RilAbbSnehaM** [comment]
Is this issue close?

**Comment by Jiggy9** [comment]
> Is this issue close?

Mention your pull request here, I'll close it

**Comment by RilAbbSnehaM** [comment]
https://github.com/Jiggy9/JCT/pull/15

**Comment by RilAbbSnehaM** [comment]
I mentioned

**Comment by Jiggy9** [comment]
Thank you for your contribution!

> I mentioned
