### ISSUE TITLE
Profile section save button not working after putting data 

### ISSUE THREAD

**Issue by RilAbbSnehaM** [Jiggy9/JCT#16]
Uploading WhatsApp Video 2024-10-07 at 22.58.56_e0b7350f.mp4…

**Comment by Jiggy9** [comment]
> Uploading WhatsApp Video 2024-10-07 at 22.58.56_e0b7350f.mp4…

You can start working on it

**Comment by nisarg107** [comment]
Solution : Upgraded firebase dependencies , changed minsdkversion and handled savechanges function in profilepage.dart. Now you can connect to firebase through firbase_cli
