### ISSUE TITLE
Missing CONTRIBUTING.md file

### ISSUE THREAD

**Issue by archanasingh11** [Jiggy9/JCT#2]
**Description:**

The `CONTRIBUTING.md` file is missing from the JCT repository. This file is essential for guiding new contributors through the process of setting up the project, adhering to coding standards, and submitting pull requests. Without it, contributors may lack clarity on how to effectively contribute to the project, which could lead to inconsistencies and confusion.

I recommend adding a `CONTRIBUTING.md` file to outline:
- Steps for setting up the repository locally.
- Branching and submission of pull requests.
- Code style guidelines and best practices.
- How to report issues and propose new features.

Please @Jiggy9 assign me this task with labels "GSSOC-Ext", "Hacktoberfest-accepted" and"level1".

**Comment by Jiggy9** [comment]
> **Description:**
> 
> The `CONTRIBUTING.md` file is missing from the JCT repository. This file is essential for guiding new contributors through the process of setting up the project, adhering to coding standards, and submitting pull requests. Without it, contributors may lack clarity on how to effectively contribute to the project, which could lead to inconsistencies and confusion.
> 
> I recommend adding a `CONTRIBUTING.md` file to outline:
> 
> * Steps for setting up the repository locally.
> * Branching and submission of pull requests.
> * Code style guidelines and best practices.
> * How to report issues and propose new features.
> 
> Please @Jiggy9 assign me this task with labels "GSSOC-Ext", "Hacktoberfest-accepted" and"level1".

You can start working on it @archanasingh11

**Comment by archanasingh11** [comment]
Hey @Jiggy9 could you also assign me any labels of "level1", "level2" and "level3".

**Comment by archanasingh11** [comment]
Hey @Jiggy9 the spelling of label "hacktoberfest-accepted" that you have provided is wrong .
