### ISSUE TITLE
UI Improvement 

### ISSUE THREAD

**Issue by ezsarthak** [Jiggy9/JCT#23]
Hello,
I would love to work on this UI and contribute to the project. 
You can give me a summary of UI or I can improve it.
can you please assign this to me?
Thank you!

**Comment by Jiggy9** [comment]
> Hello, I would love to work on this UI and contribute to the project. You can give me a summary of UI or I can improve it. can you please assign this to me? Thank you!

Already existing issue available and contributor is working on it, Thanks!
