### ISSUE TITLE
Can I add CODE OF CONDUCT.md file so that contributors know how to contribute,what to avoid and how  to behave during their contributions?

### ISSUE THREAD

**Issue by ark0078** [Jiggy9/JCT#24]
@Jiggy9 @archanasingh11 @EfrataAron @CodewithAnn @RilAbbSnehaM could you please assign me this issue?

**Comment by Jiggy9** [comment]
> @Jiggy9 @archanasingh11 @EfrataAron @CodewithAnn @RilAbbSnehaM could you please assign me this issue?

Duplicate issue, check existed issue before opening new
