### ISSUE TITLE
profile opening is not working same as change password opening

### ISSUE THREAD

**Issue by WednesdaySP** [Jiggy9/JCT#34]
https://github.com/user-attachments/assets/5517b5cf-348e-4a9e-bebd-805a043079bc

the profile tab should also open on click of the tab itself like in change password tab, but it only opens on clicking the arrow icon

**Comment by CodewithAnn** [comment]
@Jiggy9 assign this to me, let me fix it.

**Comment by WednesdaySP** [comment]
@Jiggy9  I would like to resolve this issue.

**Comment by ritik6559** [comment]
i can work on it, assign it to me, add the label of gssoc-ext and haktoberfest

**Comment by Jiggy9** [comment]
@WednesdaySP you can start working on it

**Comment by WednesdaySP** [comment]
@Jiggy9 done

**Comment by Jiggy9** [comment]
> @Jiggy9 done

Good, Send PR, I'll merge

**Comment by Jiggy9** [comment]
#41 completed
