### ISSUE TITLE
back arrows are not unfiorm within the application

### ISSUE THREAD

**Issue by WednesdaySP** [Jiggy9/JCT#35]
different types of back arrow icons are used in the app which leads to UI inconsistency
![WhatsApp Image 2024-10-08 at 17 07 44_6c9bb5f1](https://github.com/user-attachments/assets/13f1c0c8-43a1-47a3-8a9e-c82a28ff1d2d)
![WhatsApp Image 2024-10-08 at 17 07 44_094b665c](https://github.com/user-attachments/assets/118cecea-dfa8-4fb5-9bab-4a5386565a35)
![WhatsApp Image 2024-10-08 at 17 07 45_24ecd4d4](https://github.com/user-attachments/assets/157660bf-2286-4db1-aa21-8abda2367bd2)
![WhatsApp Image 2024-10-08 at 17 09 53_c9d2d3d8](https://github.com/user-attachments/assets/f870844b-1db1-4e4a-b723-b3cf51bd028f)

**Comment by Jiggy9** [comment]
@WednesdaySP you can work on it

**Comment by WednesdaySP** [comment]
@Jiggy9  i have resolved this issue, can you please add hactoberfest label also
