### ISSUE TITLE
spacing issue in  Your Complaints UI

### ISSUE THREAD

**Issue by WednesdaySP** [Jiggy9/JCT#36]
then content in Your Complains screen does not have proper spacing on the sides.
![1](https://github.com/user-attachments/assets/2219aa20-e20f-4449-a9b9-fb5c7154af0a)

**Comment by Jiggy9** [comment]
> then content in Your Complains screen does not have proper spacing on the sides. ![1](https://private-user-images.githubusercontent.com/122176467/374543117-2219aa20-e20f-4449-a9b9-fb5c7154af0a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzODg1MTksIm5iZiI6MTcyODM4ODIxOSwicGF0aCI6Ii8xMjIxNzY0NjcvMzc0NTQzMTE3LTIyMTlhYTIwLWUyMGYtNDQ0OS1hOWI5LWZiNWM3MTU0YWYwYS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwOFQxMTUwMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NWE0ZjFiOGMzN2VjMWM3NWZlZmEwNWY4ZGU0ZTJmZDU2NmUwOGVkZjM1YTVhYTdhYmM2ODk0ZjllNjIxZmRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.1-wUg51WkirHufBijSvAaZOD6MuZ-nPZWS20zNOC5Ac)

Duplicate issue, UI improving issue already exists
