### ISSUE TITLE
in profile section save data should be visible to user after input so that whenever user want to edit it should be edited 

### ISSUE THREAD

**Issue by RilAbbSnehaM** [Jiggy9/JCT#38]

**Comment by Jiggy9** [comment]
@RilAbbSnehaM you can start working now

**Comment by RilAbbSnehaM** [comment]
@Jiggy9 the Firebase Storage security rules are not allowing the user to upload files.for this, you need to update your Firebase Storage security rules to allow authenticated users to upload files.

**Comment by Jiggy9** [comment]
> @Jiggy9 the Firebase Storage security rules are not allowing the user to upload files.for this, you need to update your Firebase Storage security rules to allow authenticated users to upload files.

Mail or LinkedIn me, I'll give you  access to firebase you can modify it accordingly.

**Comment by RilAbbSnehaM** [comment]
can u snd me linkedin id @Jiggy9

**Comment by Jiggy9** [comment]
> can u snd me linkedin id @Jiggy9

You can check out it on my GitHub profile

**Comment by RilAbbSnehaM** [comment]
@Jiggy9 I snd u request u can accept and msg me I unable to msg u bcoz it req premium

**Comment by RilAbbSnehaM** [comment]
Uploading WhatsApp Video 2024-10-10 at 01.37.51_c6a512a4.mp4…

done

**Comment by RilAbbSnehaM** [comment]
@Jiggy9 close this issue
