### ISSUE TITLE
implementation of bottom nav bar in place of drawer to increase user engagement and enhance app UI

### ISSUE THREAD

**Issue by WednesdaySP** [Jiggy9/JCT#39]
![WhatsApp Image 2024-10-08 at 20 14 20_fd1094bb](https://github.com/user-attachments/assets/d3db985c-072b-427e-b4f4-79a9010c501a)
![WhatsApp Image 2024-10-08 at 20 14 20_b5f6b492](https://github.com/user-attachments/assets/a9212411-332a-4f74-8417-c8bc8a6a6977)

**Comment by CodewithAnn** [comment]
@WednesdaySP If we use bottomnav here then the user doesn't know what to do with these icons and if we use title-based nav then it might look ugly.

**Comment by WednesdaySP** [comment]
@CodewithAnn settings and feedback can be easy understood through icons by users, and there is no need of complaint monitor and emergency alert in the drawer as they are already visible on the home screen., so it is better to user bottom nav bar rather than drawer.

**Comment by Jiggy9** [comment]
@CodewithAnn you can work on it now

**Comment by rishichirchi** [comment]
Hey, I would like to work on this issue!

**Comment by CodewithAnn** [comment]
> Hey, I would like to work on this issue!

currently, I am working on it

**Comment by WednesdaySP** [comment]
@Jiggy9 I would like to work on this please assign it to me.

**Comment by Jiggy9** [comment]
> @Jiggy9 I would like to work on this please assign it to me.

Actually he is handling other issues related to UI too, so I assigned him, Looking forward to your further contributor to other issues:)

**Comment by WednesdaySP** [comment]
@Jiggy9  can you assign it to both of us?

**Comment by Jiggy9** [comment]
> @Jiggy9 can you assign it to both of us?

You both can communicate with each other, if you both agree, I don't mind, just make sure , it won't cause any conflict

**Comment by WednesdaySP** [comment]
@Jiggy9  okay 👍🏻

**Comment by CodewithAnn** [comment]
@Jiggy9 @WednesdaySP Actually, I am almost done. If you want to work with me then you can dm me on LinkedIn. https://www.linkedin.com/in/dev-anandjha/
<img src=https://github.com/user-attachments/assets/3eac8b2f-2201-45fe-b690-ab4d29947133 height="600">

**Comment by WednesdaySP** [comment]
@CodewithAnn I already did

**Comment by CodewithAnn** [comment]
@WednesdaySP Apology, I created the pull but don't worry I left some style and another part(like hiding the navbar etc..) for you in the Bottom Nav you can create a new issue, and @Jiggy9 will Assign you that. If you get conflicts on the pull you can keep your code part in styling and remove mine.

**Comment by Jiggy9** [comment]
> @WednesdaySP Apology, I created the pull but don't worry I left some style and another part(like hiding the navbar etc..) for you in the Bottom Nav you can create a new issue, and @Jiggy9 will Assign you that. If you get conflicts on the pull you can keep your code part in styling and remove mine.

Yeah If you want to work on rest styling part lemme know @WednesdaySP , I'll assign you.

**Comment by WednesdaySP** [comment]
@CodewithAnn @Jiggy9 which styling part are you guys talking about could you please explain in detail.

**Comment by Jiggy9** [comment]
> @CodewithAnn @Jiggy9 which styling part are you guys talking about could you please explain in detail.

Well you can run app and check if there's still something to modify in nav bar and make UI better in anyway, you can work on it now else I'll close this issue

**Comment by WednesdaySP** [comment]
@Jiggy9 ok I'll do it

**Comment by rishichirchi** [comment]
I'll check out the other issues!

**Comment by WednesdaySP** [comment]
@Jiggy9 I am not able to login or sign up in app due to invalid API token issue

**Comment by Jiggy9** [comment]
> @Jiggy9 I am not able to login or sign up in app due to invalid API token issue

@WednesdaySP don't worry.. Wait we're working on it.. @CodewithAnn could u check this once?

**Comment by CodewithAnn** [comment]
> @Jiggy9 I am not able to login or sign up in app due to invalid API token issue

Did you @WednesdaySP  setup the firebase for you app?

**Comment by Jiggy9** [comment]
@CodewithAnn check LinkedIn

**Comment by WednesdaySP** [comment]
@CodewithAnn  @Jiggy9  I don't have firebase access for this app

**Comment by WednesdaySP** [comment]
@Jiggy9  you can close this issue now.

**Comment by Jiggy9** [comment]
@WednesdaySP check again as code is updated, and lemme know that you can login now in app or not?

**Comment by WednesdaySP** [comment]
@Jiggy9 login is working properly
