### ISSUE TITLE
[Bug] : iOS Build Fails Due to cloud_firestore Plugin Requiring Higher iOS Deployment Target

### ISSUE THREAD

**Issue by may-tas** [Jiggy9/JCT#43]
## Bug : 
- When trying to build the Flutter app on iOS, the following error is encountered due to the cloud_firestore plugin requiring a higher minimum iOS deployment target:
- Error : The plugin "cloud_firestore" requires a higher minimum iOS deployment version than your application is targeting.
- To build, increase your application's deployment target to at least 13.0 as described at https://flutter.dev/to/ios-deploy
 Error running pod install
 Error launching application on iPhone 15 Pro Max.

## Steps to reproduce : 
- Add the cloud_firestore plugin to your Flutter project.
- Attempt to build the project using IOS emulator.
-  The build will fail with the above error message.

## Expected behavior : 
- The project should build successfully after updating the iOS deployment target to meet the minimum version required by the cloud_firestore plugin.

**Comment by may-tas** [comment]
@Jiggy9 Please assign me this issue , I can resolve it. 
Also please add hactoberfest-accepted and gssoc-ext label to it.

**Comment by Jiggy9** [comment]
> @Jiggy9 Please assign me this issue , I can resolve it. Also please add hactoberfest-accepted and gssoc-ext label to it.

Go ahead, I assigned you!

**Comment by may-tas** [comment]
Sure thanks !
