### ISSUE TITLE
[Fix Firebase Api ☠️]:  Firebase issue In Login and signup 

### ISSUE THREAD

**Issue by CodewithAnn** [Jiggy9/JCT#48]
A lot of people facing issues logging in and signing up in that app due to the wrong credentials/setup and getting API issues. 
@Jiggy9 assign this to me and  let me fix this. assign label to it under gssoc and hacktoberfest

**Comment by Jiggy9** [comment]
> A lot of people facing issues logging in and signing up in that app due to the wrong credentials/setup and getting API issues. @Jiggy9 assign this to me and let me fix this. assign label to it under gssoc and hacktoberfest

Go ahead!
