### ISSUE TITLE
[Feature Request: 🦄]: Add Localization for the app 

### ISSUE THREAD

**Issue by CodewithAnn** [Jiggy9/JCT#50]
I want to work on this specific task to enable access to the app for everyone through **localization**. This feature helps people to use the app in their language which they prefer, it's a small gesture but means a lot to them(respect for their language).

Here is the work progress.
<img src="https://github.com/user-attachments/assets/7ea4d3e0-a3f0-4dd2-98ee-4a2fbc8bf4d5" alt="Screenshot_1728632645" height= "500">

**Comment by CodewithAnn** [comment]
@Jiggy9 assign this to me so that I can proceed. Please add labels under gssoc and hecktoberfest

**Comment by Jiggy9** [comment]
> @Jiggy9 assign this to me so that I can proceed. Please add labels under gssoc and hecktoberfest

Go ahead
