### ISSUE TITLE
[Documentation]  Enhancement in Readme File adding git commands explaining how to commit and push the code. 

### ISSUE THREAD

**Issue by Open-nika** [Jiggy9/JCT#51]
**Modifications in the README.md file:**

Is there an existing issue for this?
✔️ I have searched the existing issues

Describe the Issue
Enhancement in Readme File adding git commands explaining how to commit and push the code with proper screenshots

Record
 I have read the Contributing Guidelines
 I'm a GSSOC Ext'24 contributor
 I'm a Hacktoberfest 2024 contributor
 I have starred the repository

**Comment by Open-nika** [comment]
Kindly assign the issue to me. Make sure to add the labels of Hacktoberfest,gssoc-ext and level

**Comment by Jiggy9** [comment]
> **Modifications in the README.md file:**
> 
> Is there an existing issue for this? ✔️ I have searched the existing issues
> 
> Describe the Issue Enhancement in Readme File adding git commands explaining how to commit and push the code with proper screenshots
> 
> Record I have read the Contributing Guidelines I'm a GSSOC Ext'24 contributor I'm a Hacktoberfest 2024 contributor I have starred the repository

Not needed, thank you.
