### ISSUE TITLE
overflow in login/ signup screen

### ISSUE THREAD

**Issue by WednesdaySP** [Jiggy9/JCT#52]
![WhatsApp Image 2024-10-12 at 11 21 55_039db02f](https://github.com/user-attachments/assets/1a26c7a4-30a4-48d0-87c9-4dece5df79fb)

**Comment by Jiggy9** [comment]
> ![WhatsApp Image 2024-10-12 at 11 21 55_039db02f](https://private-user-images.githubusercontent.com/122176467/375929421-1a26c7a4-30a4-48d0-87c9-4dece5df79fb.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MTM2MzksIm5iZiI6MTcyODcxMzMzOSwicGF0aCI6Ii8xMjIxNzY0NjcvMzc1OTI5NDIxLTFhMjZjN2E0LTMwYTQtNDhkMC04N2M5LTRkZWNlNWRmNzlmYi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMlQwNjA4NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iODgwZWVjMDhmYWEzN2RmOWQzYWMyMDVmNTdkYzYzY2YzYTc0NTExMjVjMWQxZjU3MTMyM2YxNGQ1OWU3MDA3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.pGNGGlcrniThU_BZ-nJtRoFAp-U8zsU4nLuhsoUn-QI)

This depends on which emulator you choose to run in android, well make it dynamic so any emulator can adapt it..
