### ISSUE TITLE
UI Improvement 🤖 : Need To improve Home page UI

### ISSUE THREAD

**Issue by CodewithAnn** [Jiggy9/JCT#58]
I want to improve the home page UI there are default UI cards that do not look good. I need to follow good design principles to look appealing.

**Comment by CodewithAnn** [comment]
@Jiggy9  please assign this issue to me.

**Comment by Jiggy9** [comment]
@CodewithAnn Gimme detailed description of ur design and ui components you willing to improve

**Comment by CodewithAnn** [comment]
@Jiggy9  I am going to follow the official material 3 design principles with some modern UI, like first there are gradient containers used to show there, and I am going to use custom colours and graphics to differentiate the container types For raising complaints there are different colour schema use and as so for other too. will be using grid view to display the custom card rather than listview. If you have any design references then I can implement that too

**Comment by Jiggy9** [comment]
> @Jiggy9 I am going to follow the official material 3 design principles with some modern UI, like first there are gradient containers used to show there, and I am going to use custom colours and graphics to differentiate the container types For raising complaints there are different colour schema use and as so for other too. will be using grid view to display the custom card rather than listview. If you have any design references then I can implement that too

Sounds good to me, go ahead!

**Comment by CodewithAnn** [comment]
> > @Jiggy9 I am going to follow the official material 3 design principles with some modern UI, like first there are gradient containers used to show there, and I am going to use custom colours and graphics to differentiate the container types For raising complaints there are different colour schema use and as so for other too. will be using grid view to display the custom card rather than listview. If you have any design references then I can implement that too
> 
> Sounds good to me, go ahead!

then assign this to me 🫡and for reference of card : 
something like this where I also implement the animation and try to implement a slider to raise a complaint
![Screenshot 2024-10-12 221948](https://github.com/user-attachments/assets/cd9012a9-6ea9-4fde-bd61-89b92fdba493)
