### ISSUE TITLE
[BUG] : Returning back from profile page leads to black screen

### ISSUE THREAD

**Issue by may-tas** [Jiggy9/JCT#59]
# Bug : 
- when you click the **back arrow** button in the profile appBar it leads to black screen.
-  small issue can be resolved easily.

![WhatsApp Image 2024-10-13 at 01 15 38](https://github.com/user-attachments/assets/e0e94d64-16f9-46e6-9e9f-e0bad7893771)

**Comment by may-tas** [comment]
@Jiggy9 please assign me this issue.

**Comment by may-tas** [comment]
@Jiggy9 Can I open an issue for setting up GoRouter package in the app.
It will significantly improve navigation in the app and we won't have to use the bulky Navigator.push .

**Comment by Jiggy9** [comment]
> @Jiggy9 Can I open an issue for setting up GoRouter package in the app. It will significantly improve navigation in the app and we won't have to use the bulky Navigator.push .

Sure go ahead.
