### ISSUE TITLE
Refactor Bottom Navigation Bar for Better Navigation Consistency and UI Enhancement

### ISSUE THREAD

**Issue by may-tas** [Jiggy9/JCT#61]
## Issues : 
- First thing is that the code for bottom navigation is too clustered and big which is not at all necessary.
- When you are navigating to any screen for e.g navigating to account page from settings tab, then the bottom navigation bar is gone and not visible.
- When you navigate to profile screen from account page then also the navigation bar is not there.
- Navigation Bar should always be sticked to the bottom screen except for some screens which are not there in bottom tab , for e.g for accounts page it is fine if the navigation bar is not there but when you navigate to profile screen from account page, the navigation bar should be present as it is a part of the tabs of navigation bar.
- Enhancing the AppBar and Making it more stylish and modern.

**Comment by may-tas** [comment]
I want to work on it, Please assign me this issue.
Thanks.

**Comment by Jiggy9** [comment]
> I want to work on it, Please assign me this issue. Thanks.

Go ahead

**Comment by Jiggy9** [comment]
@may-tas Bro make it better card, it seems like some animation honestly, I want it professional.. this time send ss me here before working on it.
