### ISSUE TITLE
Migrate deprecated apply method to declarative plugins block in Gradle script

### ISSUE THREAD

**Issue by may-tas** [Jiggy9/JCT#62]
# Description:
- Currently when you run the app you get the following warning in debug console : 
   - You are applying Flutter's app_plugin_loader Gradle plugin imperatively using the apply script method, which is deprecated and will be removed in a future release. Migrate to applying Gradle plugins with the declarative plugins block: https://flutter.dev/go/flutter-gradle-plugin-apply

## Issue : 
- The Flutter project currently applies the **_app_plugin_loader_** Gradle plugin imperatively using the **_apply_** script method.
- The **_apply_** method is deprecated and will be removed in a future release of **Gradle**.
- This could lead to build failures in the future once the deprecated method is removed.

## Solution : 
- Migrate from the deprecated apply method to the declarative plugins block in the Gradle script.
- Follow the official guidelines from Flutter for this migration: [Flutter Gradle plugin migration guide](https://flutter.dev/go/flutter-gradle-plugin-apply).

**Comment by may-tas** [comment]
@Jiggy9 I have already solved this issue, please assign me this issue so I can make the PR.

**Comment by Jiggy9** [comment]
> @Jiggy9 I have already solved this issue, please assign me this issue so I can make the PR.

That's good you can send PR.
