### ISSUE TITLE
Addition of All Contributors Photos in Readme

### ISSUE THREAD

**Issue by AnushkaChouhan25** [Jiggy9/JCT#64]
I can add all the contributor's photos in Readme file as a token of appreciation for their work. 
Like this
 
![image](https://github.com/user-attachments/assets/52625afd-80f6-4dbe-b8d4-d3832488dd51)

Please assign me this issue under gssoc-extd and hactoberfest-accepted with suitable level label, I want to contirbute in it.

**Comment by Jiggy9** [comment]
> I can add all the contributor's photos in Readme file as a token of appreciation for their work. Like this
> 
> ![image](https://private-user-images.githubusercontent.com/157525924/376057034-52625afd-80f6-4dbe-b8d4-d3832488dd51.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxMjkxMjgsIm5iZiI6MTcyOTEyODgyOCwicGF0aCI6Ii8xNTc1MjU5MjQvMzc2MDU3MDM0LTUyNjI1YWZkLTgwZjYtNGRiZS1iOGQ0LWQzODMyNDg4ZGQ1MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxN1QwMTMzNDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMGE2YWYyN2YzY2M4ZmVmMTEyYjE3MTQyNzZkYTc0NjM3YTEyNDE3NWJkNTA4Mjg5ODY1N2Q4M2NlMWI3MjAxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.TSS7fNxemRA0d7gl15VW00fFAMLVs2_rgi7UBR7rTRw)
> 
> Please assign me this issue under gssoc-extd and hactoberfest-accepted with suitable level label, I want to contirbute in it.

Sure go ahead!
