### ISSUE TITLE
[Feature Request🦄]:  Add light and dark theme mode and a toggle button

### ISSUE THREAD

**Issue by CodewithAnn** [Jiggy9/JCT#68]
There is a missign dark mode and light mode in the app. easy to switch using a toggle button.

**Comment by CodewithAnn** [comment]
@Jiggy9 please assign this to me.

**Comment by Jiggy9** [comment]
> @Jiggy9 please assign this to me.

Sure, go ahead

**Comment by tanayduddalwar** [comment]
@Jiggy9  please assign me this issue
