### ISSUE TITLE
adding Code of Conduct page

### ISSUE THREAD

**Issue by jaidh01** [Jiggy9/JCT#7]
Hi @Jiggy9 ,

I believe it would be beneficial to establish a Code of Conduct for our public repository. This would help maintain discipline and promote a respectful and inclusive community. I suggest using a framework like the one provided by the [Contributor Covenant](https://www.contributor-covenant.org/version/2/1/code_of_conduct/) as a basis for our own guidelines.

Request: - Kindly assign this issue to me and label it as `gssoc24-extd, hacktoberfest-accepted and level 1`.

**Comment by Jiggy9** [comment]
> Hi @Jiggy9 ,
> 
> I believe it would be beneficial to establish a Code of Conduct for our public repository. This would help maintain discipline and promote a respectful and inclusive community. I suggest using a framework like the one provided by the [Contributor Covenant](https://www.contributor-covenant.org/version/2/1/code_of_conduct/) as a basis for our own guidelines.
> 
> Request: - Kindly assign this issue to me and label it as `gssoc24-extd, hacktoberfest-accepted and level 1`.

Not needed

**Comment by Jiggy9** [comment]
@jaidh01 hey you can work on this issue now

**Comment by jaidh01** [comment]
Hi @Jiggy9 , 
Thank you for assigning it to me. 
I request you please add `level 1` and `hacktoberfest-accepted` label to this issue.

**Comment by Jiggy9** [comment]
> Hi @Jiggy9 , Thank you for assigning it to me. I request you please add `level 1` and `hacktoberfest-accepted` label to this issue.

Let it on me about labels

**Comment by jaidh01** [comment]
> > Hi @Jiggy9 , Thank you for assigning it to me. I request you please add `level 1` and `hacktoberfest-accepted` label to this issue.
> 
> Let it on me about labels

Hi @Jiggy9, since the PR for this issue has been merged, could you please review the labels?

**Comment by Jiggy9** [comment]
> > > Hi @Jiggy9 , Thank you for assigning it to me. I request you please add `level 1` and `hacktoberfest-accepted` label to this issue.
> > 
> > 
> > Let it on me about labels
> 
> Hi @Jiggy9, since the PR for this issue has been merged, could you please review the labels?

I assigned hacktoberfest-accepted, for level1 label work on other issues more than documention.
