### ISSUE TITLE
Add Our valuable Contributors to README.md

### ISSUE THREAD

**Issue by Anjalis14** [Jiggy9/JCT#70]
like this 

![Screenshot 2024-10-16 003413](https://github.com/user-attachments/assets/472fa3bf-fc74-4ad0-ab38-47880d041430)

**Comment by Anjalis14** [comment]
@Jiggy9 plz assign me this

**Comment by Jiggy9** [comment]
> like this
> 
> ![Screenshot 2024-10-16 003413](https://private-user-images.githubusercontent.com/156239419/376775858-472fa3bf-fc74-4ad0-ab38-47880d041430.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxMjg5NDYsIm5iZiI6MTcyOTEyODY0NiwicGF0aCI6Ii8xNTYyMzk0MTkvMzc2Nzc1ODU4LTQ3MmZhM2JmLWZjNzQtNGFkMC1hYjM4LTQ3ODgwZDA0MTQzMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxN1QwMTMwNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jODhhZDgwOTAxODk5NDgwMzMzODQ2YTI2NTUxM2Q0ODM2YWVlODY5NTVkYWIzZDVmNzY5ODI1Y2M1Y2Q5MGIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.CW5VeSY7X9FPzMHQop5jUmgRZSHN7T9zaIH5dfwfgEA)

Sure, go ahead!

**Comment by Jiggy9** [comment]
Thank you, closing it as contributor is already working on it.

> @Jiggy9 plz assign me this
