### ISSUE TITLE
UI: Improve the sign up and login screen 

### ISSUE THREAD

**Issue by CodewithAnn** [Jiggy9/JCT#72]
the auth screens are pretty basic i want to implement a modern login UI 

<img src = "https://github.com/user-attachments/assets/9d7e7cfb-e6d1-4668-9b0e-417b110bf20c" height = "400">

**Comment by CodewithAnn** [comment]
@Jiggy9 please assign this to me.

**Comment by Jiggy9** [comment]
> @Jiggy9 please assign this to me.

Sure.. go ahead!

**Comment by CodewithAnn** [comment]
@Jiggy9 you can close this now
