### ISSUE TITLE
Integrating google oAuth

### ISSUE THREAD

**Issue by Dhruv80576** [Jiggy9/JCT#75]
Integrating google oauth would help in easier login process. Can u assign this issue under hacktoberfest and gssoc label?

**Comment by Jiggy9** [comment]
> Integrating google oauth would help in easier login process. Can u assign this issue under hacktoberfest and gssoc label?

Sure implement sign up, sing in both using google.. it should he reflected in firebase as well..

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by CodewithAnn** [comment]
@Jiggy9  please assign this issue to me if there is no running process.

**Comment by Jiggy9** [comment]
@Dhruv80576 what's your progress till now?

**Comment by Dhruv80576** [comment]
There was some problem with gradle version. Will create a pr today

**Comment by Jiggy9** [comment]
> There was some problem with gradle version. Will create a pr today

Make sure to fork latest repo and then work on it, to resolve problem and avoid merge conflict

**Comment by Dhruv80576** [comment]
Yeah sure
