### ISSUE TITLE
i wnat work on ongoing complaints page

### ISSUE THREAD

**Issue by singhtrivendra** [Jiggy9/JCT#76]
i want to work on ongoing complaints page,app tilte is wrong and there should be withdraw complints button on detailed complaint page click on it sholud remove that complaints as by misktake if user dagging left should get redo option.

**Comment by Jiggy9** [comment]
> i want to work on ongoing complaints page,app tilte is wrong and there should be withdraw complints button on detailed complaint page click on it sholud remove that complaints as by misktake if user dagging left should get redo option.

You can work on it, but make sure it'll be also reflected in firebase

**Comment by singhtrivendra** [comment]
ok

**Comment by nisarg107** [comment]
can you assign this to me?

**Comment by Jiggy9** [comment]
> ok

What's the progress till now?

**Comment by singhtrivendra** [comment]
@Jiggy9 i have added button but i am unable to build logic to delete it from firebase
![WhatsApp Image 2024-10-21 at 19 53 00_90813040](https://github.com/user-attachments/assets/5ddeccbe-12f9-4bad-bda7-52b051a1b760)

**Comment by Jiggy9** [comment]
> can you assign this to me?

You can work on this

**Comment by Jiggy9** [comment]
> @Jiggy9 i have added button but i am unable to build logic to delete it from firebase ![WhatsApp Image 2024-10-21 at 19 53 00_90813040](https://private-user-images.githubusercontent.com/120274602/378469513-5ddeccbe-12f9-4bad-bda7-52b051a1b760.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2MDE0MDUsIm5iZiI6MTcyOTYwMTEwNSwicGF0aCI6Ii8xMjAyNzQ2MDIvMzc4NDY5NTEzLTVkZGVjY2JlLTEyZjktNGJhZC1iZGE3LTUyYjA1MWExYjc2MC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMlQxMjQ1MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MDlkYzcwNTY0ZWM3ZmNkNzUwMzAyNjkzMDgwN2RiYjA4ZmVmZTk1M2ZhZWI4OTg4ODQ3YjkwMTU1MTlhNTZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.nZAOSOTXGfQpvtqMujVlMH1K4Lx8AtD_Ny5SPfFSIvU)

It's fine, you did good, whoever send me PR with complete work, I'll merge it :)
