### ISSUE TITLE
Enhancing Readme.md 

### ISSUE THREAD

**Issue by neeru24** [Jiggy9/JCT#8]
Hi,

I’ve been exploring the project and appreciate the work you’ve done so far. I’d like to propose an update to the README.md file to provide a more comprehensive overview of the website. Here are a few ideas I have in mind:

A detailed description of the website's current features and functionalities.
A clear vision for the final project and any future enhancements.
Embedded links for additional reference.
I believe these updates could enhance user understanding and engagement with the project. If you're open to it, I’d love to contribute.

I’m committed to continually improving the quality of our documentation.

Thank you!

**Comment by EfrataAron** [comment]
Hi. yes, you can start working on this.

**Comment by neeru24** [comment]
> Hi. yes, you can start working on this.

Can you please add the "gssoc-ext".... These labels too

**Comment by Jiggy9** [comment]
#9 completed
