### ISSUE TITLE
Add GitHub Repository Stats to README.md

### ISSUE THREAD

**Issue by Karthik3904** [Jiggy9/JCT#81]
The issue involves adding a table to display repository statistics, such as the number of stars, forks, issues, and pull requests, directly in the README.md file. This will help contributors and users track the activity and contributions in the repository at a glance.

### Steps to Implement:
1. Create a table in the README.md file displaying the following repository statistics:
   - Stars
   - Forks
   - Open Issues
   - Open Pull Requests
   - Closed Pull Requests
2. Use markdown syntax to include badges or icons for each statistic, along with dynamic links to the corresponding sections of the repository.

### Expected Behavior:
The README.md file will contain a neatly formatted table that displays real-time repository statistics, making the repository's activity more visible and engaging for contributors and users.

### Additional Information:
- This enhancement will make the repository more user-friendly by providing visibility into its overall activity.
- The table can be dynamically updated by using GitHub shields or other badge services to fetch real-time stats.

### Screenshot (for reference):
- (Attach the screenshot you provided for a visual representation of the desired table layout.)
![WhatsApp Image 2024-10-21 at 15 01 28_2cc264e3](https://github.com/user-attachments/assets/87bfe750-0016-47b7-9d64-be62f43b61cb)

**Comment by Jiggy9** [comment]
> The issue involves adding a table to display repository statistics, such as the number of stars, forks, issues, and pull requests, directly in the README.md file. This will help contributors and users track the activity and contributions in the repository at a glance.
> 
> ### Steps to Implement:
> 1. Create a table in the README.md file displaying the following repository statistics:
>    
>    * Stars
>    * Forks
>    * Open Issues
>    * Open Pull Requests
>    * Closed Pull Requests
> 2. Use markdown syntax to include badges or icons for each statistic, along with dynamic links to the corresponding sections of the repository.
> 
> ### Expected Behavior:
> The README.md file will contain a neatly formatted table that displays real-time repository statistics, making the repository's activity more visible and engaging for contributors and users.
> 
> ### Additional Information:
> * This enhancement will make the repository more user-friendly by providing visibility into its overall activity.
> * The table can be dynamically updated by using GitHub shields or other badge services to fetch real-time stats.
> 
> ### Screenshot (for reference):
> * (Attach the screenshot you provided for a visual representation of the desired table layout.)
>   ![WhatsApp Image 2024-10-21 at 15 01 28_2cc264e3](https://private-user-images.githubusercontent.com/182359908/378841341-87bfe750-0016-47b7-9d64-be62f43b61cb.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2MDEyNzIsIm5iZiI6MTcyOTYwMDk3MiwicGF0aCI6Ii8xODIzNTk5MDgvMzc4ODQxMzQxLTg3YmZlNzUwLTAwMTYtNDdiNy05ZDY0LWJlNjJmNDNiNjFjYi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMlQxMjQyNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ODZkMjZiYzQ0MDMwZTcyMjA1YjMwMzkwYjc5Njc4OTMyMWQxZjcxMDcyMWRjNGM2NmQxMDk5YWE4N2ZjYjU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.YGBj7eFH-WFyyEdM_y1B0K5wboNyNgHnqBbdIJEhizs)

Not needed
